### ISSUE TITLE
Formal governance ?

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#10]
Beyond the de factor hierarchy, there is no formal way to address problems or official titles or anything at all.

I suggest we work on some formal description and succession queues for the haxe foundation (at least on the public site).

@ncannasse you are the better suited to redact something or design such a thing, i would not be schocked if you had super powers etc, but I deeply think Daniel G. has a point in saying we have to clear who makes what and who has a say.

I also think that the strategic members deserve to know how far their say can go. 

I like how mozilla (https://www.mozilla.org/en-US/about/governance/) formalised theirs, we can make something much more lightweight but I think it should be formalized so that the hf team gain a solid legitimacy.

The eventual votes possibilities should also be clarified.

**Comment by Merelleya** [comment]
I am in favour of that. It would also spread the heat of the flames and it ties in nicely with the aim to be more clear and open about what we expect from "contributors" (in whichever way) in order to be able to address their contributions and process them effectively.

**Comment by Merelleya** [comment]
Just so that there is no misunderstanding: I am in favour of making clear who is responsible for what (like we were planning with the who-is-who-page). 

I think making sure we have proper communication lines and make clear how to address/reach the Foundation should be enough to enable the community to address problems with us. Other than that I can not exactly comment, since I have not been part of the community for all that long.

**Comment by ncannasse** [comment]
Yes, we had some plans to clarify roles by doing the "team" page (I should get back the photos we took at WWX next week or so)

**Comment by delahee** [comment]
Aside roles, there should be a process for the community to ask feedback, estimated roadmap, and who gets a vote in what. I think also community a wishlist would be good.

**Comment by ncannasse** [comment]
I think it's important to listen to feedback and get input from various community people. That's what we did at HF meeting on sunday morning at WWX.

However, i don't think that design-by-comity is a good solution when it comes to deciding things such as language features or what gets included into std, etc. Most people don't know the inner workings of the compiler, what technically makes sense or not, etc. We are here to listen to their problems but in the end it's up to us to find the right solution.

**Comment by delahee** [comment]
I a totally fine with that, but then making it clear in plain text in a "formal contribution process and actors" is a very good idea so that we don't get revolutions coming out of every sick joke I make... :)

**Comment by Merelleya** [comment]
maybe you should just refrain from sick jokes xD.

**Comment by delahee** [comment]
That s fair, I ll try for at least two weeks, then will create a private
repo for those called nyarlatotep... :)

**Comment by Merelleya** [comment]
In my head there is that chibi version of you looking all starry-eyed at a can of worms...

**Comment by elliott5** [comment]
I think @delahee 's idea of adopting a lightweight version of the Mozilla governance framework is really strong.

I also agree with @ncannasse that his "benign dictatorship" is an important component in making Haxe what it is.

**Comment by kulick** [comment]
I love the tone here and agree with all comments.  :+1:

Personally however, I will be sad if @delahee stops making bad jokes.  ;)

**Comment by Merelleya** [comment]
comment moved.

**Comment by ncannasse** [comment]
We cannot have something like mozilla with actual roles since we are a much much smaller organization were everybody does some quite specific things, but I'm in favor of updating our haxe foundation pages with as much information as we can, in order to be more transparent, regarding the following things:
- who is haxe foundation
- what are our goals
- how we are financed
- how do we spend the money
- how people can contribute / help + guidelines about what we can consider for inclusion
- why design by committee is a bad idea for a language :)
- what are our relations with [3rd party haxe libraries]
- etc

**Comment by Simn** [comment]
We give answers to most of these questions already. What's missing is the whole finance section.

**Comment by ncannasse** [comment]
I meant, in a much detailed way than it is right now

**Comment by ncannasse** [comment]
Our about page is currently short, which is fine for an about page, but we should have more details on other pages http://haxe.org/foundation/

**Comment by Merelleya** [comment]
I think we should look at the whole "Foundation" section and structure the information a little better. The who-is-who page and a more detailed "article" on what we do and why and how should also be included soon. I will give this some thought and see if I can come up with an outline.

**Comment by ncannasse** [comment]
Once thing I would like to highlight is that HF is not like a SF startup that just came our of nowhere. Having a small graphical timeline showing when haxe was created, how it evolved (1.0,2.0,3.0) and telling that HF was setup to make it grow even further should help with this.

I'm always a bit worried about the negative part of this ("I had never heard of it before") so we have to find a good way to explain that before HF, it was just a "simple" OSS project with no actual communication (which is was somehow)

**Comment by Simn** [comment]
I'm torn on this. I get your "never heard of it before" argument, but at the same time something that has been around for 10 years has a strong notion of stability.

**Comment by elliott5** [comment]
The 10-years-of-Haxe story is very strong indeed and provides solid evidence of stability.

"Why have I never heard of it before?" because it was built by programmers for programmers, without  some wealthy corporation pushing it along to further their own agenda. Those businesses who know about Haxe have been quietly using it for many years as a way to reduce their software development costs and feel little need to tell their competitors. Only recently, after the formation of the Haxe Foundation, has there been a platform to build on this established success and reach out to the wider software development community.

**Comment by Merelleya** [comment]
Will re-open separate issues
