### ISSUE TITLE
Honorary members

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#11]
Beyond what is happening in the community (and I am really unhappy about this mess), we should embark big third party haxe communities and have them on board on this github.

Namely : 

HaxePunk
HaxeFlixel
The openfl team
Silex

I will be better if we show our goodwill rather than stay in the current fuzzy hiatus.
I believe, we cannot make a better haxe without these teams they should have a word in what is here.

**Comment by Merelleya** [comment]
Anybody has access to this board and can open issues. However, the primary aim is to coordinate _us_ and not to coordinate everybody or have discussions that are not related to actionable projects. Nor is this to be the primary repository for political discussions. If necessary, we may consider opening another Repository for that (might actually be a good idea). But in here, I would like to focus on the core happenings and core project management, since this is what I need to adress at the moment to be able to coordinate future endeavors.

You may have noted, that there is no "discussion" label as such xD.

I will leave this issue open for a week to gather feedback on whether we want a discussion repository and then, if necessary, direct the discussions somewhere else.

**Comment by elliott5** [comment]
@Merelleya I think there is a need to have a place to discuss ecosystem-wide issues, and bring in the parties that @delahee suggests. This is because they are the key to driving more developers to use Haxe.

My guess is that most developers do not come to use Haxe because it is a wonderful language, they come because it gives them access to cross-platform development stacks developed by third parties like HaxePunk, HaxeFlixel, OpenFL and others. 

Clearly I hope that my own TARDISgo project will eventually bring Go programmers to Haxe in the same way. But be clear, I would not have chosen Haxe as my target language without OpenFL / Lime / NME existing.

To make the Haxe language the success it should be, the Foundation does needs to work very closely with these influential third-party Haxe development teams. Which repo to use does not matter, but listening to and supporting your star developers does.

**Comment by Merelleya** [comment]
I will read this as "I agree, we should have a repository to discuss meta topics concerning ecosystem-wide issues with the above suggested parties", right?

**Comment by elliott5** [comment]
Yes @Merelleya and with any other parties who add value to the core Haxe sales proposition. Where would any platform be without it's application framework developers?

**Comment by Merelleya** [comment]
My job description just keeps getting longer xD

**Comment by kulick** [comment]
I agree that including those groups will lead to a better, stronger Haxe community.  I also think that those teams may be able to help with /some/ of the goals/issues covered here.  That said, I understand the thinking behind keeping this repository about PM execution and creating another space for broader coordination.  I support either/both.

**Comment by Merelleya** [comment]
For my taste, we have a lot of discussion with very few actionable tasks at the moment. However, since we have never had this sort of discussion before now, I will wait a few weeks more, to see if things calm down a little. Otherwise, I would be concerned about "finding" the "stuff to do" within all the threads.

We have had some input from community members here, too, so I think in some cases this might be the right space. However, I would not want to have a second version of what is currently being done in/with the google group. If it came to that extent, we would definitely have to move the discussions somewhere else.

**Comment by kulick** [comment]
Sounds good to me!

**Comment by delahee** [comment]
You are all right, nonetheless there is a problem about what i call "community intersection". There is clearly sub communities not "aferring" to haxe foundation. Those sub communitites are vital to us but there are defiance building. At least let's keep that in mind and try to open bridges. On my side, i'll try to reach them when opportunities come.

Ok for close to me. I'll get back with something more concrete if my discussion efforts goes well.

**Comment by Merelleya** [comment]
I will close this for now and keep an aye on how the PW Repo is being used in the meantime. We may open a discussion Repo at some point in the future, if it gets "unmanageable", but I think it will be alright.
