### ISSUE TITLE
public financial reports

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#13]
As ask by Someone, there should be a page listing public financial reports and we should ensure they are available to report engines like société.com.

**Comment by ncannasse** [comment]
I'm fine with it, but Daniel asked about financial reports at WWX and when he got them he complained that we are not looking good because of our small budget. I'm not sure how we should address this. If we have huge numbers we would surely be happy to communicate on them, in the meanwhile I'm not sure what for this would be useful.

**Comment by Merelleya** [comment]
@delahee please use appropriate labels for you issues.

First of all, it was not asked by someone, it was asked by Daniel Glazman specifically and only by him. We do not have anything to hide so I don't see why we should not upload the financial report somewhere. 

However, I would not go on much about it. Keep it short and sweet, because otherwise we will always come across as somewhat defensive. On the other hand, it might be nice for people to see that things can be accomplished without much money and it will disperse any "Nicolas is getting rich with Haxe" sentiments. On the whole, I have very little experience in open source thingys and am not aware of best practices So I am very open to (experience and data-backed) suggestions.

Also, I think it would be much more interesting to publish an actual budget for the next year instead of a financial report. In fact, a report does not make much sense without a budget.

Finally, I would like to point out that, even though it is important to listen to constructive feedback and implement changes based on said feedback, we should not let anybody make us nervous.

**Comment by ncannasse** [comment]
As I said i'm fine with publishing the financial reports, as you said we have nothing to hide and it's better for people not to make strange ideas about how things are handled here.

But I'm just questioning what would be the correct way to link such reports : while as @Merelleya said it's nice to see how much we can do with a small budget when you're familiar with Haxe, OTOH if you're just evaluating Haxe and see the small budget, we don't want this kind of information to turn down people based on misleading perception

**Comment by Merelleya** [comment]
@delahee disregard my comment on labels. I am just finding out that those are only available to me ~.~

**Comment by Merelleya** [comment]
@ncannasse maybe just present them at the WWX each year and otherwise have them available on request? I really don't know.

**Comment by delahee** [comment]
@Merelleya here in France medium to big companies are legally required to publish financial reports. I think it is a good practice, and especially for a charity/foundation of some sort

@ncannasse like juraj said "only fools are afrait to look like fools" The numbers are fine for me, he asked it, he have it. I am ok for not to much publicity if you are really afraid but frankly you should not be shy. It is much more healthy not to have members questionning people about where the money goes than pleasing investors imvho. honestly I ask this for other reasons (adopters askings) much broader than Daniel case, that 's why he was not my main subject.

I'll go alongside you but don't be afraid ;)

**Comment by elliott5** [comment]
@Merelleya I agree that briefly presenting the Foundation's financial reports at each WWX is a really good idea, but they would also need to be on-line somewhere if only to demonstrate that the Foundation is not FIFA ;)

Daniel Glazman has wider experience of the open-source world than me, so if he says that the Foundation's annual budget is very small, I believe him. But I draw different conclusions. First it means that the way the Foundation operates now to support the Haxe language is very cost effective - so well done! Second it means that there are huge opportunities for gaining additional financial support in future.

However, in 2015 there will be some potential investors in Haxe, both venture capitalists (as Daniel Glazman experienced) and technology managers in large corporations, who will be unwilling to take a risk on using the language because the support offered by the Foundation seems too fragile. Indeed Tivo could only justify using Haxe to their board because they felt they could take the compiler in-house if they had to.

The size of the budget is not an issue that has a quick-fix, but it should provide an important aiming-mark for the Foundation. 

I believe that Haxe is primarily a business tool for saving software development costs. Once technology managers can see those savings being realised, they should be willing to support the Foundation financially to enable those cost savings to continue. 

Recruiting more financial support from the existing user-base must therefore be a key management issue for the Foundation, especially as the more financial support the Foundation has, the more credible it will seem to outsiders.

The good news is that success in this area is only a matter of time. But by paying close attention to the communication and sales processes, that time could be made shorter.

**Comment by Simn** [comment]
> The good news is that success in this area is only a matter of time.

I might be naive but I totally agree with this. I have seen a steady growth over the past years and see no sign of it slowing down. That's also why I consider talks like Daniel's to be detrimental because they feed unrest and impatience which generally don't lead to good business decisions.

Of course we could just halt all development and dump all our resources into a marketing campaign with press releases and other fancy things. We might even gain some visibility that way but in the end it's something that we call Strohfeuer in Germany: It bursts up quickly but dies down equally fast. No, I very much prefer to keep at a steady pace and be able to react to market development.

I see no reason to be shy about our budget. Haxe didn't have a real budget at all until the Haxe Foundation was established. I worked on it pro bono for almost a year and Nicolas keeps doing so as well, as well as many other contributors and maintainers. And even if we all get hit by a bus at the same time: The whole thing is still open source and others could take over.

So what I want to say is: Let's be transparent about our finances and not get depressed over some managers deciding that we're not worthy of their investment. I'm confident enough to think that's their loss as much as it is ours.

**Comment by elliott5** [comment]
Agreed @Simn, I'm confident those managers who choose not to invest in Haxe now, will come to regret it later.

**Comment by Merelleya** [comment]
Ok. Could we discuss a specific format so we can move ahead with this?

**Comment by ncannasse** [comment]
We have the PDF from our accountant, but they are in french and not much usable by normal people

**Comment by Simn** [comment]
> We have the PDF from our accountant, but they are in french and not much usable by common people

Yes m'lord... more work?

**Comment by ncannasse** [comment]
I just got Skyped by fiene about how aristocratic it was sounding :) in french it works well, I didn't meant   it that way of course, "normal people" was the correct word, I'll edit :)

**Comment by Simn** [comment]
> We just got Skyped by fiene about how aristocratic it was sounding :) in french it works well, we didn't meant it that way of course, "normal people" was the correct word, we'll edit :)

ftfy :)

**Comment by kulick** [comment]
You guys crack me up.  ;)

**Comment by MatthijsKamstra** [comment]
wxx 2015 started this, should it not be finished?

**Comment by ncannasse** [comment]
I'm still not sure on which form we should publish this. Any insights?

**Comment by delahee** [comment]
You could just publish the pdf "as is", if some volunteer really want to extract data, he will. American foundations seem to publish taxes too but imho there is no point for our size.

Bonus : leave one or two sentence about growth or not, expectations or not.

ref : https://www.mozilla.org/en-US/foundation/annualreport/2013/
ref : http://www.apache.org/foundation/records/

**Comment by Merelleya** [comment]
I agree with David on this one. Just publish them as is, if applicable, we can include a small statement. but other than that I would not invest too much work into it. The people who are interested in them, will know how to read them.

**Comment by Merelleya** [comment]
@ncannasse I am moving this to "Review before close". If you agree, we can close this and just set up a task to do this when its time.

**Comment by ncannasse** [comment]
The PDF have already been made available through mail on [haxe] group, I'm copying the link there so it can be added somewhere on the website https://drive.google.com/file/d/0Bxr4dvgTFeHzSTF5TDhGSFU1M2c/view?usp=sharing

**Comment by Simn** [comment]
I'll go ahead and close this. As Nicolas says the financial report is available for people who are interested in it, and I see no reason to rub it into everyone's face.
