### ISSUE TITLE
Answering your own questions on Stackoverflow

### ISSUE THREAD

**Issue by Merelleya** [HaxeFoundation/Project-Management#24]
Apparently it is allowed to post Questions to Stackoverflow and answer them yourself. Is anybody up for posting some FAQs with answers there?

**Comment by dogles** [comment]
Related: there are tons of Q&A threads in the Google group. I found several that would be applicable for Stack Overflow, e.g.:

https://groups.google.com/forum/#!topic/haxelang/e27o1jLXGIg
https://groups.google.com/forum/#!topic/haxelang/b61U-qfmYM0
https://groups.google.com/forum/#!topic/haxelang/CSmI3GR2cqs

That's just in the past day or two. Is there a way to get these cross-posted, or try to migrate people to Stack Overflow for these types of questions instead of the Google Group?

**Comment by Simn** [comment]
I suppose we should also talk about support channels in general. Some time ago Fiene and I thought about improving http://haxe.org/community/community-support.html by adding something like this under the current content:

<hr/>

<h1>What goes where?</h1>

<h5>You did something awesome with Haxe and would like to share it with the community?</h5>

<div class="span4">
    <ul class="nav nav-tabs nav-stacked">
        <li><a href="https://twitter.com/search?q=%23haxe" title="#haxe tag on Twitter"><i class="fa fa-twitter"></i> #haxe</a></li>
        <li><a href="https://plus.google.com/communities/103302587329918132234" title="Haxe Google+ Community"><i class="fa fa-google-plus"></i> Google+</a></li>
    </ul>
</div>

<h5 style="clear:left">You are looking for input or want to discuss a Haxe-related topic?</h5>

<div class="span4">
    <ul class="nav nav-tabs nav-stacked">
        <li><a href="http://groups.google.com/group/haxelang?hl=en"><i class="fa fa-envelope-o "></i> Google Group</a></li>
    </ul>
</div>

<h5 style="clear:left">You have a technical question and are looking for live support?</h5>

<div class="span4">
    <ul class="nav nav-tabs nav-stacked">
        <li><a href="http://webchat.freenode.net/?channels=haxe" title="Webchat for #haxe on FreeNode (IRC)"><i class="fa fa-comments-o"></i> IRC (#haxe / Freenode)</a></li>
    </ul>
</div>

<h5 style="clear:left">You have a general question?</h5>

<div class="span4">
    <ul class="nav nav-tabs nav-stacked">
        <li><a href="http://groups.google.com/group/haxelang?hl=en"><i class="fa fa-envelope-o "></i> Google Group</a></li>
        <li><a href="http://stackoverflow.com/questions/tagged/haxe" title="Questions tagged 'Haxe' on Stack Overflow"><i class="fa fa-stack-exchange"></i> Stack Overflow</a></li>
    </ul>
</div>

<h5 style="clear:left">You want to report an issue?</h5>

<div class="span4">
    <ul class="nav nav-tabs nav-stacked">
        <li><a href="https://github.com/HaxeFoundation/haxe/issues" title="Issue Tracker for Haxe on Github"><i class="fa fa-github"></i> Compiler bug reports (Github)</a></li>
        <li><a href="https://github.com/HaxeFoundation/haxe.org/issues" title="Issue Tracker for haxe.org on Github"><i class="fa fa-github"></i> Website bug reports (Github)</a></li>
        <li><a href="https://github.com/HaxeFoundation/HaxeManual/issues" title="Issue Tracker for HaxeManual on Github"><i class="fa fa-github"></i> Manual bug reports (Github)</a></li>
    </ul>
</div>

**Comment by markknol** [comment]
Wouldnt it be weird to answer own questions? But if this is allowed, Who wouldnt want to gain some stackoverflow points? 

As sidenote, I recently renamed lots of posts with haXe to Haxe.

**Comment by larsiusprime** [comment]
Stack Overflow actually explicitly encourages you to answer your own
questions, because it's not just a site about providing answers to a
specific question so-and-so asks, it's designed to build up as an
SEO-optimized database of common Q&A's for any given technology.

On Sat, Jun 6, 2015 at 3:55 PM, Mark Knol notifications@github.com wrote:

> Wouldnt it be weird to answer own questions? But if this is allowed, Who
> wouldnt want to gain some points? I'm in.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HaxeFoundation/Project-Management/issues/24#issuecomment-109647870
> .

## 

www.fortressofdoors.com -- Games, Art, Design

**Comment by markknol** [comment]
Thats good to know. While Im very often on stackoverflow (hehe who isnt??!), I have never seen a question that has been answered by same user. Maybe we should also encourage the irc users to ask more via stackoverflow.

**Comment by larsiusprime** [comment]
It might also just be good practice to have some people ask common
questions and have other people immediately go in and answer them. Get the
ball rolling and maybe more likely to get better results that way.

**Comment by Merelleya** [comment]
Now, I would need for someone to take a lead on this and move forward by, for instance, compiling a list of questions as well as coordinating with the others?

**Comment by markknol** [comment]
I tried it for fun to write own question and answer them. 
http://stackoverflow.com/q/30933523/508029

I added Haxe examples in some global tags descriptions too, some who also have code snippets of other languages :smiley: it would be nice if other haxe-developing stackoverflow users also could take some time on such stuff. Also there are quite some tags (transpilers, crossplatform) or the gamedev stack site etc which can be watched, since we have the interesting answers, right? If anyone is in need of questions and answers, (s)he could check the irc logs too, all the information is there (but unsorted). Since this can never be "fixed" by one person, maybe we could ask on the googlegroups for stackoverflow-haxe-evangelists?

**Comment by Merelleya** [comment]
Yeah we should put out a call to action on that.

Maybe we should include some short guidelines/description of what to do, too.

**Comment by delahee** [comment]
Am seeing more and more of this kind of discussion : https://twitter.com/incredibletoy/status/617377375131709440

about abstracts, typedef and other "exotic" structural typing features.

Maybe some sponsored stackoverflow question could cover these more efficiently than me in 140 char ;)

1- Why do haxe "abstract" exists ? 
2- What is the different use of a "typedef" 

etc...

@simn could this be linked to some part of our documentation effort ? I mean like pretty much copy-pasting doc parts in stackoverflow ?

**Comment by ncannasse** [comment]
I'm planning some article series about some of these topics

**Comment by delahee** [comment]
@andyli saw your effort with manual links but I think the people are looking at the underlying motives, needs, samples, why they profundly need this here. :)

**Comment by andyli** [comment]
@delahee Yes, I can see that some dedicated articles or Q&As are useful. I was just pointing out in the tweets that the terminologies were misused ;)

**Comment by back2dos** [comment]
I think using stackoverflow more is a good idea. The platform already has good moderation, high visibility and discoverability. Our community is already active there. We have a 80% accepted answer rate there, which is really good if we can maintain that while growing - and I think we can. 

Also, much of the more traffic we have there, the more it should cause collateral visibility in the respectively accompanying tags (e.g. a question tagged #haxe #javascript should raise awareness among those who watch the JS tag).

Does anyone have issues with designating stackoverflow the appropriate place for Q&A?

**Comment by Merelleya** [comment]
I still need someone to take the lead on this, so if anyone feels inclined, I would be grateful for the help!

**Comment by Merelleya** [comment]
Just talked to @jasononeil and it seems that there is more activity on stackoverflow now. I will close this for now and we will see how it goes.
