### ISSUE TITLE
Priority of resolving issues

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/Project-Management#28]
In the main haxe repo, when filtering the label "bug" in the issue list, I can see a few issues that are opened more than a year ago. I am not sure but isn't that bugs should be fixed at highest priority? 

Among other things, I guess proper issue management is also important for the language's future development.

**Comment by Simn** [comment]
I think we're doing fine in that area. If an issue is open for a long time it's probably because nobody has yet found a good solution for it. These things can happen in compiler development.

It's perfectly fine to pick some low-hanging fruits as long as you don't go bike shedding constantly. I really don't see what you would like to see changed here.

**Comment by kevinresol** [comment]
What about some voting system like [this](http://feedback.gitlab.com/forums/176466-general) or [this](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2104557-feature-request-break-on-next-statement)? That would also help the Haxe team to focus on things that are most wanted.

**Comment by Simn** [comment]
I don't think that is necessary. I usually make it very transparent what is and isn't being worked on. Several factors play into the prioritization of issues and popularity within the community is only one of them.

**Comment by kevinresol** [comment]
Closing this. The topic is better discussed [here](https://github.com/HaxeFoundation/Project-Management/issues/14)
