### ISSUE TITLE
haxe.org social connectors

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#34]
Regarding SEO etc, the haxe.org main page should have social connectors like g+1 fb like etc as it dramatically improves discoverabilty and SEO. 

ex : 
https://www.facebook.com/pages/Python/283172211807319?fref=ts

**Comment by Merelleya** [comment]
That is not true, unfortunately. Social connectivity has no impact on search engine results as such. There is a slight correlation between sites that have good social profiles and their performance in SEO, but it is unclear whether the social activity actually causes search results to be better or not. It may as well be that extensive social marketing often goes hand in hand with SEO (as in - if you pay attention to one, you also pay attention to the other).

Also, the use of social connectors has lessened over the years, since nowadays, people just share a link if they want to without having to be prompted. In some circles, social connectors are even seen as "trying too hard". Also, I would tackle social media marketing before I go putting in connectors. Finally, they might also sort of clutter the design on the site.

Anyway, if the general consensus is "put them in" I would put them in, even though I am not too fond of them but it is not very high on the priorities (from my perspective).

**Comment by markknol** [comment]
I think it would make more sense to have such social buttons on our new blog.

**Comment by Merelleya** [comment]
+1
For the articles on the blog I think it would be nice to have, yes, since that would be fresh content we are looking to have people share. good point ^-^

**Comment by delahee** [comment]
Social connectors have an effect on seo as backlinks and serp, as the seo for the said social media and Google scans for g+1 so saying l... they don't impact contradicts my experience as Web dev... Even if it has lost power it is a highly cheap way to gain traction.

So I insist we should have g+1 and fb like targeting haxe.org.

http://www.forbes.com/sites/jaysondemers/2015/01/27/6-social-media-practices-that-boost-seo/

It doesn't take that much time and the design crippling is manageable not to say arguable :)...

**Comment by Simn** [comment]
Could someone fill me in on what a "social connector" is?

**Comment by Merelleya** [comment]
They are like this:

![capture](https://cloud.githubusercontent.com/assets/5541210/8203306/07ac08ee-14e1-11e5-9f91-c8260c207d8e.PNG)

@markknol could you check if you can find a version to fit the website design or even incorporate it into your new design? They should be somewhere not too obtrusive, though. Maybe we can settle for something similar to python?

![python](https://cloud.githubusercontent.com/assets/5541210/8203360/82d0c884-14e1-11e5-8501-7850a37a472b.png)

I like how they have their menu.

**Comment by Simn** [comment]
I don't like the ones that make you like/follow something automatically, but I wouldn't mind just linking to our social media.

**Comment by delahee** [comment]
sidenote : Python communication is top notch, fine for me.

**Comment by markknol** [comment]
http://projects.stroep.nl/haxe/navigation/ < Yes I already planned this, maybe we should call the main menu item "connect" or something.

**Comment by Merelleya** [comment]
Socialize or Connect with us, I think. Thank you so much, Mark. You're a veritable star.

**Comment by MatthijsKamstra** [comment]
It seems that some movement is made in that direction, but done wrongly. I agree more with the solution from @markknol : if you decide to use "easy way to connect" it should be present on all pages AND directly point to link not to an extra page (http://haxe.org/community/community-support.html)  

From a design point of view I like the design made by @markknol also better 
I like the gray a default color, menus more subtile, left aligned, the design feels calmer.

@markknol design
![screen shot 2015-10-12 at 22 41 55](https://cloud.githubusercontent.com/assets/907219/10438205/828fcc78-7132-11e5-9ccf-4afcf8a1f0b0.png)

Current design
![screen shot 2015-10-12 at 22 42 02](https://cloud.githubusercontent.com/assets/907219/10438206/829560b6-7132-11e5-8e6c-d8df452a6878.png)

We should try to "hide" that search box  (it's hideous ); there are probably some rules that are attached for using a google search box... but dang what is that thing in your face.

There is also something going on with the svg logo when it's that small (it looks like white anti-aliasing) so if I would be a design-guru I would suggest to create a small version of the logo (probably without the "flaps") 
![screen shot 2015-10-12 at 22 50 45](https://cloud.githubusercontent.com/assets/907219/10438407/b9c8c144-7133-11e5-921f-da47b7af50a5.png)

But I am not a design guru..... :smile:

**Comment by MatthijsKamstra** [comment]
btw they should be in the footer as well

**Comment by markknol** [comment]
I think the logo at small size is good enough as it is right now. It depends on the screen and browser how it is rendered.

**Comment by MatthijsKamstra** [comment]
Firefox, Safari, Chrome (OSX)
![screen shot 2015-10-13 at 09 46 49](https://cloud.githubusercontent.com/assets/907219/10448810/a418d210-718f-11e5-8e81-7b6c5a29de14.png)

But again, there are bigger issues :smile:

**Comment by MatthijsKamstra** [comment]
It's nice that everybody responds, but what is the next step?
And I just don't know so that's why I ask: who is responsible for the website?

It seems everybody was very motivated 4 months ago, but adding 4 links to the website shouldn't take that long. Again I am happy to help (html/css) to put some of these issues to rest.

**Comment by Merelleya** [comment]
Jason is doing some work on the website this week and next week too. I will keep closing issues as they are being dealt with. I general, @jasononeil deals with website changes^^

**Comment by Simn** [comment]
What's the status here?

**Comment by markknol** [comment]
Well its there. I was actually waiting for @jasononeil to build it into the site, but maybe I will get my hands dirty on this task myself..? I find it looking pretty already in the haxedevelop site.

**Comment by Merelleya** [comment]
Get into it!

@jasononeil is not available at the moment so I think if we want something done, we will have to figure it out ourselves.
