### ISSUE TITLE
http://devdocs.io/

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#35]
A mozilla guy told me we should be here : http://devdocs.io/. I'll try to see what it takes.

**Comment by markknol** [comment]
All we need to do is vote https://trello.com/c/5WlUgFkZ/213-haxe

**Comment by markknol** [comment]
I asked the community to vote https://groups.google.com/forum/m/#!topic/haxelang/owGzROSWq8Q

**Comment by Merelleya** [comment]
@delahee please close if this satisfies your investigation into the topic^^.

**Comment by delahee** [comment]
If it is ok to you, I ll close when our content is available so that the
issue pester us to take more actions :)
Le 15 juin 2015 21:31, "Josefiene Pertosa" notifications@github.com a
écrit :

**Comment by delahee** [comment]
The author is not in the process of adding haxe, he hints us to do it. 

Is anyone willing ?

**Comment by Simn** [comment]
Then what was the vote for...?

Maybe @markknol could look into it after his well-deserved vacation. For me this doesn't have a very high priority though.

**Comment by ibilon** [comment]
I can give it a try today,
looking at the open pull requests for new language support it doesn't seem too complicated and the process is well explained on the wiki.

**Comment by Merelleya** [comment]
Thank you, @ibilon

**Comment by ibilon** [comment]
Small update, so I didn't have any problem running their code, I added the couple of files needed, the api is parsed. It's not complete yet, it doesn't go into the packages but there's a method for that so it'll be ok and there are styling issues but that's for the end.

Problem though, here's how their docs are organized: on the first level is a list of languages/softwares, haxe is added here. And then for each language there is the type list which then contains the classes.
All of this is pretty far from the package structure we have, it's more high level like for the c++ entry: algorithm, containers, input/output...
Which is not something we have, so nothing to scrape here.
A "solution" would be for example for `File` to be in `sys.io`, which itself wouldn't be in `sys`, since there's no type in types. But that's ugly.

Not really sure what to do, any ideas?

**Comment by delahee** [comment]
@ibilon
Hi Valientin, thanks for taking ownership.

I suggest you just present targets like packages ? 

each target would have a section then we could just have a brief overview of the whole haxe api (wa can design something reusable here)

Maybe you can share a balsamiq mockup on dropbox so that we can iterate together ? 

Thanks a lot !

**Comment by MatthijsKamstra** [comment]
I am not sure how important this part of documentation is, but 4 months ago it seemed important. Perhaps this issue should be closed?

**Comment by markknol** [comment]
@ibilon What is the status of this?

**Comment by ibilon** [comment]
Sadly nowhere, couldn't find time for this.

But my initial reserve still apply, there's no support for package/namespace, so I don't see how we can have a good representation of the haxe api there.

But I'll push my modifications for the parsing in case someone has a good idea on how to make the display.

**Comment by Merelleya** [comment]
@ibilon is there anything we can do to help with this? Maybe its worth putting out a call to the community to see if someone has any good ideas.

Otherwise I will close this, adding a reminder to maybe revisit it at a later date.

**Comment by markknol** [comment]
Just saw this on twitter! Great work! https://twitter.com/JbIPS/status/706784714259099648

**Comment by clemos** [comment]
gg @JbIPS :)

**Comment by JbIPS** [comment]
You're welcome! Hope it will help spread Haxe consciousness :wink:

**Comment by delahee** [comment]
Bravo @JbIPS !
