### ISSUE TITLE
Summary - Board Meeting 31.05.2015

### ISSUE THREAD

**Issue by Merelleya** [HaxeFoundation/Project-Management#4]
Here is the summary from the Board meeting:

https://github.com/HaxeFoundation/Project-Management/wiki/Meeting-Notes---Board-Meeting---31.05.2015

I have tried to be detailed, but  I don't think that I got everything.

Please comment on completeness, correctness and discuss if necessary. At the end of the discussion I would like to have a correct and complete Wiki Page as well as a list with points that need separate issues for further discussion/project management.

**Comment by nadako** [comment]
what's `Haxe-Call-In functionality`?

**Comment by dpeek** [comment]
@nadako it's something Tivo were using to talk to hxcpp from Objective C, and possibly to hxjava from normal Java (not sure about second one). Basically they built iOS/Android apps with platform tools/language and then used common business/service logic written in Haxe (the same they use on the STB)

**Comment by Simn** [comment]
> switch to a 6 monthly, fixed-date release cycle

I don't mind trying that but I'm not sure it's gonna work.

> release as-is whether or not everything we "would like" is finished

This makes it sound as if we were waiting for some fancy feature which delayed our release. This is not the case. Everything that caused a delay was a real regression and it's not possible to make a stable release with known regressions. I don't even think we could make a non-stable release with known regressions.

**Comment by elliott5** [comment]
The fact that the minutes of the meeting have been published and will be published in future is really important. Obviously lots of very sensible things were said at the meeting. There are just two areas where I would like to cheer the Foundation on.

As the Haxe team members are mostly technologists, the whole "Communication" activity is not something that is a natural behaviour for most. So there is always a big temptation for team members to avoid doing this type of work by putting it off until a later date. That's why it is so important to force yourselves to do it! As the meeting minutes suggest, the key team members should have a communication meeting every week and issue at least one communication every week. No excuses. This is an approach I have been part of myself as a director of a commercial organisation, so I know how difficult and painful it is to sustain long-term, but I also know how effective it can be as your message gradually gets out and the organisation becomes better known.  

I think it is really important to have a roadmap for the development of the Haxe compiler, the Haxe ecosystem (mostly not within your direct control) and the Haxe foundation itself. It allows everyone to have a sense of the direction the community intends to go in, which should support long-term buy-in by technical managers considering adopting Haxe within their organisations. The road-map should be updated every six-months, timed alongside a 6-month release cycle. @Simn is quite right that unstable-releases must not be made, so further self-discipline is required to impose a feature-freeze say 2-months before each planned release, with a beta-release say 1-month before the planned release. Users value reliability and predictability, Haxe needs to give it to them.

**Comment by Merelleya** [comment]
Hi Elliot!

Welcome to this discussion. 

Just to clarify one point. We did not agree to have weekly meetings and publish notes on those and we will also not externalize _all_ our project meeting notes for the sheer stress it would put on resources. 

What we can and will do:
- We will have quarterly team meetings and publish notes
- I will encourage everybody to have additional meetings to keep the lines of communication open. Notes on these may be shared on a case-by-case basis
- I will periodically reach out to people to get an update that can and will be shared.
- We are thinking about publishing a weekly update or just give @skial some weekly details to be included with the roud-ups.

Lets not overdo this from the get-go. I think quarterly team meetings and additional one-on-one or smaller group things will already require some coordination.

Having some notes each week is ok, as long as I won't have to try to get everybody to actually "meet". Maybe we can just implement a "send Fiene stuff to post by Tuesday each week". But even then, this will fluctuate, seeing as not everybody is working on this full time.

**Comment by elliott5** [comment]
That sounds wonderful Fiene.

All I want to do is cheer the team on, sympathize that "communications" is really difficult, and so suggest you find strategies to keep doing it ... which you seem to be doing. 

You are very wise to "not overdo this from the get-go", sorry if I read too much into the notes and got over-excited!

As you will know, the audience to communicate with are not just existing Haxe users (who are very well served by @skial as you say), but more importantly technology opinion-formers in organisations that have yet to use Haxe. But I should probably write some thoughts on that in some other thread.

Thank you for welcoming me to the discussion Fiene, I hope I can make some constructive contributions. However, as an outsider, I am bound to make some ill-informed comments sometimes. I hope you and others in the community will forgive me when I do.

**Comment by dogles** [comment]
A more detailed version of this minutes doc would be great introductory post for the Haxe dev blog ;)

**Comment by kulick** [comment]
(Just back to Cali and sorting through action items...)

So happy to see the great organization here.  Go team!  =)

The summary looks fairly complete to my memory.  Nice work!

Regarding haxe "call-in"...I have an action item to make public the TiVo repository with our haxe call-in thinking, use case matrix and sample code so expect to see that over the next few weeks.  We're currently collating all the raw information into a more digestable, high-level summary.

Also, we aren't wedded to the name "call-in".  The name might suck, actually, so feel free to propose alternatives.

**Comment by Merelleya** [comment]
Updated the page. moving this to closed. Thanks everybody!
